config/routes.rb
Rails.application.routes.draw do

  root 'en_words#index'
  get 'en_words/word_h1'
  get 'en_words/word_h2'
  get 'en_words/word_h3'
  get 'en_words/word_j1'
  get 'en_words/word_j2'
  get 'en_words/word_j3'
  

  namespace :api, { format: 'json' } do
    namespace :v1, { format: 'json' } do 
      get 'en_words/h1'
      get 'en_words/h2'
      get 'en_words/h3'
      get 'en_words/j1'
      get 'en_words/j2'
      get 'en_words/j3'
      post 'en_words/search'
      post 'en_words/detail'
      resources :en_words
    end
  end
  
  resources :en_words

end

app/models/en_word.rb
class EnWord < ActiveRecord::Base
end

app/controllers/api/v1/en_words_controller.rb
module Api
  module V1
    class EnWordsController < ApplicationController
    skip_before_filter :verify_authenticity_token

      def index
         @en_words = EnWord.all
         render json: @en_words
      end
      
      def h1
         @en_words = EnWord.where(grade: "h1")
         render json: @en_words
      end
      
      def h2
         @en_words = EnWord.where(grade: "h2")
         render json: @en_words
      end
      
      def h3
         @en_words = EnWord.where(grade: "h3")
         render json: @en_words
      end
      
      def j1
         @en_words = EnWord.where(grade: "j1")
         render json: @en_words
      end
      
      def j2
         @en_words = EnWord.where(grade: "j2")
         render json: @en_words
      end
      
      def j3
         @en_words = EnWord.where(grade: "j3")
         render json: @en_words
      end
      
      def search
         params = request.body.read
         logger.debug("params")
         logger.debug(params)
         logger.debug("params")
         @en_words = EnWord.where("name like '%#{params}%'") if !params.nil?
         render json: @en_words
      end
      
      def detail
         params = request.body.read
         logger.debug("params")
         logger.debug(params)
         logger.debug("params")
         @en_words = EnWord.find_by(name: params) if !params.nil?
         render json: @en_words
      end
        
    end
  end
end

app/controllers/en_words_controller.rb
class EnWordsController < ApplicationController
    http_basic_authenticate_with name: "sagae", password: "s19930528"

    require 'nokogiri'
    require 'open-uri'

    def index
      @en_words = EnWord.all
      @q        = EnWord.search(params[:q])
      @results = @q.result(distinct: true)
    end
    
    def new
        @en_word = EnWord.new
    end
    
    def create
     @en_word = EnWord.new(en_word_params)
     if @en_word.save
       redirect_to root_path
     else
       render 'en_words/new'
     end
    end
    
    def edit
      @en_word = EnWord.find(params[:id])
    end
    
    def destroy
      @en_word = EnWord.find(params[:id])
        if @en_word.delete
         flash[:success] = "deleted"
        end
        redirect_to root_path
    end
    
    def show
      @en_word = EnWord.find(params[:id])
    end
    
    def update
        @en_word = EnWord.find(params[:id])
        @en_word.update(en_word_params)
        redirect_to root_path
    end
    
    def word_h1
        doc = Nokogiri::HTML(open("http://www.eigo-duke.com/tango/kou1.html"))

        @en_words = EnWord.where(grade: "h1")

        if @en_words.blank?
        
            ## 動詞
            doc.css("#_HPB_TABLE_3_C_081023234310 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "v" + i.to_s
                  puts @en_word[:grade] = "h1"
                  @en_word.save!
              end
            end
        
            doc.css("#_HPB_TABLE_3_C_081023234310 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "v" + i.to_s, grade: "h1")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
        
        
        
            ## 名詞
            doc.css("#_HPB_TABLE_3_C_081023234440 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "n" + i.to_s
                  puts @en_word[:grade] = "h1"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023234440 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "n" + i.to_s, grade: "h1")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            ## 形容詞
            doc.css("#_HPB_TABLE_3_C_081023234530 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "a" + i.to_s
                  puts @en_word[:grade] = "h1"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023234530 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "a" + i.to_s, grade: "h1")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            
            ## 副詞
            doc.css("#_HPB_TABLE_3_C_081023234619 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "ad" + i.to_s
                  puts @en_word[:grade] = "h1"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023234619 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "ad" + i.to_s, grade: "h1")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            
            ## 前置詞・接続詞
            doc.css("#_HPB_TABLE_3_C_081023234654 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                   puts @en_word[:name] = doc.inner_text
                   puts @en_word[:number] = "o" + i.to_s
                   puts @en_word[:grade] = "h1"
                   @en_word.save!
               end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023234654 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "o" + i.to_s, grade: "h1")
                    # 意味
                   puts @en_word[:meaning] = doc.inner_text
                   @en_word.save!
            end
        end
    
        redirect_to root_path
    end
    
    
    def word_h2

        doc = Nokogiri::HTML(open("http://www.eigo-duke.com/tango/kou2.html"))

        @en_words = EnWord.where(grade: "h2")

        if @en_words.blank?
            ## 動詞
            doc.css("#_HPB_TABLE_3_C_081023234945 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "v" + i.to_s
                  puts @en_word[:grade] = "h2"
                  @en_word.save!
              end
            end
        
            doc.css("#_HPB_TABLE_3_C_081023234945 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "v" + i.to_s, grade: "h2")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
        
        
        
            ## 名詞
            doc.css("#_HPB_TABLE_3_C_081023235147 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "n" + i.to_s
                  puts @en_word[:grade] = "h2"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023235147 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "n" + i.to_s, grade: "h2")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            ## 形容詞
            doc.css("#_HPB_TABLE_3_C_081023235257 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "a" + i.to_s
                  puts @en_word[:grade] = "h2"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023235257 > tbody > tr> td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "a" + i.to_s, grade: "h2")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            
            ## 副詞
            doc.css("#_HPB_TABLE_3_C_081023235352 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "ad" + i.to_s
                  puts @en_word[:grade] = "h2"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023235352 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "ad" + i.to_s, grade: "h2")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
            
            
            ## 前置詞・接続詞
            doc.css("#_HPB_TABLE_3_C_081023235439 > tbody > tr > td.hpb-cnt-tb-cell3").each_with_index do |doc, i|
                if i != 0
                    @en_word = EnWord.new
                    # 英単語
                  puts @en_word[:name] = doc.inner_text
                  puts @en_word[:number] = "o" + i.to_s
                  puts @en_word[:grade] = "h2"
                  @en_word.save!
              end
            end
            
            doc.css("#_HPB_TABLE_3_C_081023235439 > tbody > tr > td.hpb-cnt-tb-cell4").each_with_index do |doc, i|
                    i += 1
                    @en_word = EnWord.find_by(number: "o" + i.to_s, grade: "h2")
                    # 意味
                  puts @en_word[:meaning] = doc.inner_text
                  @en_word.save!
            end
        end
    
        redirect_to root_path
    end
    
    
    def word_h3

        doc = Nokogiri::HTML(open("http://www.eigo-duke.com/tango/kou3.html"))

app/helpers/en_words_helper.rb
module EnWordsHelper
end

app/views/en_words/_index.html.erb
<table class="ui celled table">
  <thead>
    <tr>
    <th>ID</th>
    <th>名前</th>
    <th>意味</th>
    <th>番号</th>
    <th>がくねん</th>
    <th>管理</th>
    </tr>
 </thead>
  <tbody>
    <% en_words.each do |en_word| %>
        <tr>
         <td ><%= en_word.id %></td>
         <td><%= link_to"#{en_word.name}", en_word, { :target => "_blank"}  %></td>
         <td ><%= en_word.meaning %></td>
         <td ><%= en_word.number %></td>
         <td ><%= en_word.grade %></td>
         <td>
          <%= link_to "編集", edit_en_word_path(en_word.id), { :class => "ui olive button" } %>
          <%= link_to "削除", en_word, { :class => "ui red button", method: :delete, data: { confirm: "本当に削除してもいいですか？" }} %>
         </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/en_words/edit.html.erb
    <% if @en_word.errors.any? %>
      <div class="ui negative message">
      <i class="close icon"></i>
        <% @en_word.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    
<%= form_for(@en_word, html: {class: 'ui form'}) do |f| %>
<div class="ui raised segment">
    
    <div class="field">
      <label>名前</label>
      <%= f.text_field :name, class: "" %>
    </div>
    
    
    <div class="field">
      <label>意味</label>
      <%= f.text_field :meaning, class: "" %>
    </div>
    
    <div class="field">
      <label>番号</label>
      <%= f.text_field :number, class: "" %>
    </div>
    
    
    <div class="field">
      <label>学年</label>
      <%= f.text_field :grade, class: "" %>
    </div>
    
  <div class="actions">
    <%= f.submit "更新", class: 'ui button'%>
  </div>
</div>
<% end %>

app/views/en_words/index.html.erb
<div class="ui grid">
      <%= render 'en_words/index', en_words: @en_words if @results.nil? %>
      <%= render 'en_words/index', en_words: @results if !@results.nil? %>
  </div>
</div>

app/views/en_words/new.html.erb
    <% if @en_word.errors.any? %>
      <div class="ui negative message">
      <i class="close icon"></i>
        <% @en_word.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    
<%= form_for(@en_word, html: {class: 'ui form'}) do |f| %>
<div class="ui raised segment">
    
    <div class="field">
      <label>名前</label>
      <%= f.text_field :name, class: "" %>
    </div>
    
    
    <div class="field">
      <label>意味</label>
      <%= f.text_field :meaning, class: "" %>
    </div>
    
    <div class="field">
      <label>番号</label>
      <%= f.text_field :number, class: "" %>
    </div>
    
    
    <div class="field">
      <label>学年</label>
      <%= f.text_field :grade, class: "" %>
    </div>
    
  <div class="actions">
    <%= f.submit "登録", class: 'ui button'%>
  </div>
</div>
<% end %>

app/views/en_words/show.html.erb
<div class="ui two column centered grid">
  <div class="column">
        <table class="ui celled striped table">
          <thead>
            <tr><th colspan="3">
              <%= @en_word.name %>
            </th>
          </tr></thead>
          <tbody>
            <tr>
              <td>ID</td>
              <td><%= @en_word.id %></td>
            </tr>
            <tr>
              <td>名前</td>
              <td><%= @en_word.name %></td>
            </tr>
            <tr>
              <td>番号</td>
              <td><%= @en_word.number %></td>
            </tr>
            <tr>
              <td>学年</td>
              <td><%= @en_word.grade %></td>
            </tr>
            </tbody>
        </table>
  </div>
</div>