config/routes.rb
Rails.application.routes.draw do

  root 'en_words#index'
  get 'en_words/word_h1'
  get 'en_words/word_h2'
  get 'en_words/word_h3'
  get 'en_words/word_j1'
  get 'en_words/word_j2'
  get 'en_words/word_j3'
  

  namespace :api, { format: 'json' } do
    namespace :v1, { format: 'json' } do 
      get 'en_words/h1'
      get 'en_words/h2'
      get 'en_words/h3'
      get 'en_words/j1'
      get 'en_words/j2'
      get 'en_words/j3'
      post 'en_words/search'
      post 'en_words/detail'
      resources :en_words
    end
  end
  
  resources :en_words

end

app/views/layouts/_header.html.erb
<div class="ui segment">
  <h3 class="ui right aligned header">
    <%= link_to "新規登録", new_en_word_path %>
  </h3>
  <h3 class="ui center aligned header">
      <div class="ui action input">
        <%= search_form_for @q do |f| %>
        
          <%= f.search_field :name_cont, :placeholder => "名前" %>
          <%= f.search_field :meaning_cont, :placeholder => "意味" %>
          <%= f.search_field :number_cont, :placeholder => "番号" %><br/>
          <%= f.search_field :grade_cont, :placeholder => "学年" %>

          <%# 検索ボタン %>
          <%= f.submit :class => "ui button"%>
        <% end %>
      </div>
  </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' if controller.action_name == "index" %>
<%= yield %>

</body>
</html>